modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/HardcoreRevival/issues"

[[mods]]
modId="hardcorerevival"
version="${file.jarVersion}"
displayName="Hardcore Revival"
displayURL="https://blay09.net/mods/hardcorerevival"
logoFile="hardcorerevival-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Help your friends back up after they die (if you can make it in time).
'''

[[dependencies.hardcorerevival]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hardcorerevival]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hardcorerevival]]
    modId="balm"
    mandatory=true
    versionRange="[5.0.0,)"
    ordering="NONE"
    side="BOTH"
